data_dir: '/home/steve/Desktop/projects/noname/artemis_project/data/'
train_data_dir: '/home/steve/Desktop/projects/noname/artemis_project/data/dataset/train/'
test_data_dir: '/home/steve/Desktop/projects/noname/artemis_project/data/dataset/test/'
model_dir: '/home/steve/Desktop/projects/noname/artemis_project/data/models/'
shared_scripts_dir: '/home/steve/Desktop/projects/noname/artemis_project/scripts/shared/'
seed: 0
test_size: 0.2
max_length_aminos: 1078
min_length_aminos: 0
train: {
  epochs: 1,
  buffer_size: 50000,
  batch_size: 64,
  train_size: 1200,
  test_size: 300,
  learning_Rate: 0.0001
}
model: {
  timesteps: 1078,
  encoding_vec: 1,
  num_labels: 1918
}
